seed: 42
num_generations: 512
num_simulations_per_batch: 128
num_batches: 10000

priors:
  num_hosts:
    dist: choice
    kwargs:
      values:
        - 1024
        - 2048
        - 4096
  num_transmitted_alleles:
    dist: randint
    kwargs:
      minval: 2
      maxval: 6
  chi:
    dist: uniform
    kwargs:
      minval: 0.0
      maxval: 1.0
  mu:
    dist: loguniform
    kwargs:
      minval: 1.0e-9
      maxval: 1.0e-7
  sw:
    dist: uniform
    kwargs:
      minval: -0.999
      maxval: 0.0
  st:
    dist: uniform
    kwargs:
      minval: 0.0
      maxval: 1.0
  p_init:
    dist: uniform
    kwargs:
      minval: 0.0
      maxval: 1.0

output:
  store: outputs/malaria.zarr
  overwrite: true
  num_batches_per_write: 8
  chunks:
    num_simulations: ${num_simulations_per_batch}
    num_generations: ${num_generations}
    num_states: 16
  compression:
    enabled: true
    codec: blosc
    cname: zstd
    clevel: 5
    shuffle: shuffle
  write_empty_chunks: false

hydra:
  job:
    chdir: false
